<?php

namespace App\Repository;

use App\Entity\SpecialOffer;
use App\Service\LoggerService;
use Doctrine\ORM\EntityManager;

/**
 * Class OfferRepository
 * @package App\Repository
 */

class OfferRepository extends AbstractRepository implements RepositoryInterface {

    /**
     * OfferRepository constructor.
     * @param EntityManager $entityManager
     * @param LoggerService $loggerService
     */
    public function __construct(EntityManager $entityManager, LoggerService $loggerService) {
        parent::__construct($entityManager, $loggerService);
    }

    /**
     * @return SpecialOffer[]
     */
    public function getAll(){
        return $this->entityManager->getRepository(SpecialOffer::class)->findAll();
    }

    /**
     * @param array $fields
     * @return object|SpecialOffer
     */
    public function get(array $fields){
        return $this->entityManager->getRepository(SpecialOffer::class)->findOneBy($fields);
    }

    /**
     * @param object $entity
     * @return bool
     */
    public function save($entity) {
        return parent::save($entity); // TODO: Change the autogenerated stub
    }

    public function update($entity) {
        return parent::update($entity); // TODO: Change the autogenerated stub
    }

}