<?php

namespace App\Repository;

use App\Entity\VoucherCode;
use App\Service\LoggerService;
use Doctrine\ORM\EntityManager;

/**
 * Class VoucherRepository
 * @package App\Repository
 */

class VoucherRepository extends AbstractRepository implements RepositoryInterface {

    /**
     * VoucherRepository constructor.
     * @param EntityManager $entityManager
     * @param LoggerService $loggerService
     */
    public function __construct(EntityManager $entityManager, LoggerService $loggerService) {
        parent::__construct($entityManager, $loggerService);
    }

    /**
     * @return VoucherCode[]
     */
    public function getAll(){
        return $this->entityManager->getRepository(VoucherCode::class)->findAll();
    }

    /**
     * @param array $fields
     * @return object VoucherCode
     */
    public function get(array $fields){
        return $this->entityManager->getRepository(VoucherCode::class)->findOneBy($fields);
    }

    /**
     * @param object $entity
     * @return bool
     */
    public function save($entity) {
        return parent::save($entity); // TODO: Change the autogenerated stub
    }

    /**
     * @param object $entity
     * @return bool
     */
    public function update($entity) {
        return parent::update($entity); // TODO: Change the autogenerated stub
    }

    /**
     * @param $entities
     * @return bool
     */
    public function saveBulk($entities) {
        return parent::saveBulk($entities);
    }

}